### ISSUE TITLE
能把如何生成 android 版本的 libchinese_tts.so 的项目和配置开源出来吗？

### ISSUE THREAD

**Issue by nanfei01055** [SchweitzerGAO/SummerTTS-Android#1]
我的c++水平有限，试了但不知道怎么从源项目编译出 Android 版的 .so，我不是在java中调用的，我用的其它语言，需要从c++源码编译对接

**Comment by nanfei01055** [comment]
我终于编译出来了，但它很慢，synthesize 一句十个汉字的声音，需要 20 秒

**Comment by nanfei01055** [comment]
编译成 release，正常了，1到2秒，不错

**Comment by SchweitzerGAO** [comment]
不好意思现在才看到😂如果没问题的话，我就先close了啊，有问题随时reopen

**Comment by watersoft123** [comment]
> 我的c++水平有限，试了但不知道怎么从源项目编译出 Android 版的 .so，我不是在java中调用的，我用的其它语言，需要从c++源码编译对接

这个编译过程有教程吗？我想学习一下，谢谢

**Comment by SchweitzerGAO** [comment]
@watersoft123 不好意思现在才看到，我最近比较忙，可能没时间写详细教程了，这个project也是很久之前做的，具体细节我也记不太清楚，你可以先放到android studio里面编译下看看
